import { useState } from 'react';
import { Link } from 'react-router-dom';
import { BusinessDesign } from './BusinessDesign';
import { navigationFor, roleLabels } from './capabilities';
import type { Role } from './capabilities';
import { Badge, EmptyState, ErrorState, LoadingState, Pending } from '../ui/States';

export function DesignCatalog() {
  const [role, setRole] = useState<Role>('tecnico');
  const [pageId, setPageId] = useState('mi-legajo');
  const pages = navigationFor(role).filter(page => page.id !== 'perfil');
  const page = pages.find(item => item.id === pageId) || pages[0];
  return <div className="design-layout"><header className="design-header"><Link to="/login" className="brand"><span className="brand-mark">F</span>FieldServiceApp</Link><Link className="button button-secondary" to="/login">Ir al ingreso</Link></header><main id="main-content" className="design-main"><div className="page-heading"><div><p className="eyebrow">Módulo 1 / catálogo de diseño</p><h1>La base, antes de conectar los datos.</h1><p className="lede">Navegación, componentes y recorridos con sus dependencias visibles.</p></div><Badge tone="warning">Diseño sin datos reales</Badge></div><div className="design-toolbar"><div className="form-field"><label htmlFor="design-role">Contexto de diseño</label><select id="design-role" value={role} onChange={e => { setRole(e.target.value as Role); setPageId(''); }}>{Object.entries(roleLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><small>Este selector no cambia permisos de una sesión.</small></div><div className="form-field"><label htmlFor="design-page">Pantalla</label><select id="design-page" value={page.id} onChange={e => setPageId(e.target.value)}>{pages.map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select></div></div><section className="design-preview"><div className="page-heading compact"><div><p className="eyebrow">{roleLabels[role]}</p><h2>{page.label}</h2><p>{page.description}</p></div></div><BusinessDesign key={`${role}-${page.id}`} page={page} technicalNotes roles={[role]} /></section><section className="component-section"><p className="eyebrow">Componentes reutilizables · ejemplos de presentación</p><h2>Estados claros, sin resultados inventados</h2><div className="states-grid"><LoadingState /><EmptyState /><ErrorState message="Ejemplo visual de un error. No se ha enviado una solicitud." requestId="EJEMPLO-SIN-SOLICITUD" /><Pending title="Consulta pendiente">El formulario permanece bloqueado. No se reemplaza el selector por un campo libre de UUID.</Pending></div></section><footer className="design-footer">Contrato activo: main ee63080 (88 operaciones, 87 paths) · calendario_vigencias/proyeccion_documental/proyeccion_documental_backlog implementados con adaptador real, activación detrás de feature flags · pantallas de negocio sin integrar.</footer></main></div>;
}
